---
abstract: 'Text::MicroTemplate on the Plack'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-TMT
provides:
  Plack::Middleware::TMT:
    file: lib/Plack/Middleware/TMT.pm
    version: 0.02
requires:
  Carp: 0
  Plack::Middleware: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
  Text::MicroTemplate::File: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Plack-Middleware-TMT
version: 0.02
